default_install_hook_types:
  - pre-commit
  - commit-msg
  - pre-push
fail_fast: true
repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v4.11.3
    hooks:
      - id: commitizen
        stages: [ commit-msg ]

  - repo: https://github.com/astral-sh/uv-pre-commit
    rev: 0.9.24
    hooks:
      - id: uv-lock

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.14.11
    hooks:
      - id: ruff-check
        args: [ --fix ]
      - id: ruff-format

  - repo: https://github.com/executablebooks/mdformat
    rev: 1.0.0
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-ruff
          - ruff

  - repo: https://github.com/rohaquinlop/complexipy-pre-commit
    rev: v4.2.0
    hooks:
      - id: complexipy

  - repo: local
    hooks:
      - id: mypy
        name: mypy
        language: system
        entry: uv run mypy .
        stages: [ pre-commit ]
        pass_filenames: false
        types: [ python ]
      - id: mypy-plugin-test
        name: mypy plugin test
        language: system
        entry: uv run mypy test/typing/test_mypy_plugin.py
        pass_filenames: false
        stages: [ pre-commit ]
      - id: pytest
        name: pytest
        language: system
        entry: uv run pytest
        pass_filenames: false
        stages: [ pre-push ]
