default_install_hook_types:
  - pre-commit
  - commit-msg
  - pre-push
fail_fast: true
repos:
  - repo: local
    hooks:
      - id: commitizen
        name: commitizen
        entry: uv run cz check
        args: [--allow-abort, --commit-msg-file]
        language: unsupported
        stages: [ commit-msg ]

      - id: uv-lock
        name: uv lock
        entry: uv lock
        pass_filenames: false
        language: unsupported
        stages: [ pre-commit ]

      - id: ruff-check
        name: ruff check
        entry: uv run ruff check
        args: [--fix]
        language: unsupported
        stages: [ pre-commit ]
        types: [ python ]

      - id: ruff-format
        name: ruff format
        entry: uv run ruff format
        language: unsupported
        stages: [ pre-commit ]
        types: [ python ]

      - id: mdformat
        name: mdformat
        entry: uv run mdformat
        language: unsupported
        stages: [ pre-commit ]
        types: [ markdown ]

      - id: complexipy
        name: complexipy
        language: unsupported
        entry: uv run complexipy
        stages: [ pre-commit ]
        types: [ python ]

      - id: mypy
        name: mypy
        language: unsupported
        entry: uv run mypy
        stages: [ pre-commit ]
        types: [ python ]

      - id: mypy-plugin-test
        name: mypy plugin test
        language: unsupported
        entry: uv run mypy test/typing/test_mypy_plugin.py
        pass_filenames: false
        stages: [ pre-commit ]

      - id: pytest
        name: pytest
        language: unsupported
        entry: uv run pytest
        pass_filenames: false
        stages: [ pre-push ]
